export const fieldConvertConfig = {
  header: [
    'fullName',
    'label',
    'description',
    'inlineHelpText',
    'type',
    'externalId',
    'required',
    'unique',
    'defaultValue',
    'formula',
    'trackHistory',
    'trackTrending',
    'displayFormat',
    'displayLocationInDecimal',
    'scale',
    'precision',
    'visibleLines',
    'length',
    'maskChar',
    'maskType',
    'picklistFullName',
    'picklistLabel',
    'formulaTreatBlanksAs',
    'referenceTo',
    'relationshipLabel',
    'relationshipName',
    'relationshipOrder',
    'deleteConstraint',
    'reparentableMasterDetail',
    'writeRequiresMasterRead',
    'summarizedField',
    'summaryForeignKey',
    'summaryOperation',
    'summaryFilterItemsField',
    'summaryFilterItemsOperation',
    'summaryFilterItemsValue',
  ],
  picklistDelimiter: ';',
};
export const fieldRetrieveConfig = {
  header: [
    'fullName',
    'label',
    'description',
    'inlineHelpText',
    'type',
    'externalId',
    'required',
    'unique',
    'defaultValue',
    'formula',
    'trackHistory',
    'trackTrending',
    'displayFormat',
    'displayLocationInDecimal',
    'scale',
    'precision',
    'visibleLines',
    'length',
    'maskChar',
    'maskType',
    'picklistFullName',
    'picklistLabel',
    'formulaTreatBlanksAs',
    'referenceTo',
    'relationshipLabel',
    'relationshipName',
    'relationshipOrder',
    'deleteConstraint',
    'reparentableMasterDetail',
    'writeRequiresMasterRead',
    'summarizedField',
    'summaryForeignKey',
    'summaryOperation',
    'summaryFilterItemsField',
    'summaryFilterItemsOperation',
    'summaryFilterItemsValue',
  ],
  fieldExtension: 'field-meta.xml',
};
export const fieldGenerateConfig = {
  xmlSetting: {
    version: '1.0',
    encoding: 'UTF-8',
    xmlns: 'http://soap.sforce.com/2006/04/metadata',
  },
  defaultValues: {
    AutoNumber: {
      fullName: null,
      externalId: 'false',
      label: null,
      required: null,
      type: 'AutoNumber',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayFormat: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Checkbox: {
      fullName: null,
      externalId: null,
      label: null,
      required: null,
      type: 'Checkbox',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: 'false',
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Currency: {
      fullName: null,
      externalId: null,
      label: null,
      required: 'false',
      type: 'Currency',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: '0',
      precision: '18',
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Date: {
      fullName: null,
      externalId: null,
      label: null,
      required: 'false',
      type: 'Date',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    DateTime: {
      fullName: null,
      externalId: null,
      label: null,
      required: null,
      type: 'DateTime',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Email: {
      fullName: null,
      externalId: 'false',
      label: null,
      required: 'false',
      type: 'Email',
      trackHistory: null,
      trackTrending: 'false',
      unique: 'false',
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Location: {
      fullName: null,
      externalId: null,
      label: null,
      required: 'false',
      type: 'Location',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: 'false',
      scale: '0',
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Number: {
      fullName: null,
      externalId: 'false',
      label: null,
      required: 'false',
      type: 'Number',
      trackHistory: null,
      trackTrending: 'false',
      unique: 'false',
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: '0',
      precision: '18',
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Percent: {
      fullName: null,
      externalId: null,
      label: null,
      required: 'false',
      type: 'Percent',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: '0',
      precision: '18',
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Phone: {
      fullName: null,
      externalId: null,
      label: null,
      required: 'false',
      type: 'Phone',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Picklist: {
      fullName: null,
      externalId: null,
      label: null,
      required: 'false',
      type: 'Picklist',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    MultiselectPicklist: {
      fullName: null,
      externalId: null,
      label: null,
      required: 'false',
      type: 'MultiselectPicklist',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: '4',
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Text: {
      fullName: null,
      externalId: 'false',
      label: null,
      required: 'false',
      type: 'Text',
      trackHistory: null,
      trackTrending: 'false',
      unique: 'false',
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    TextArea: {
      fullName: null,
      externalId: null,
      label: null,
      required: 'false',
      type: 'TextArea',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    LongTextArea: {
      fullName: null,
      externalId: null,
      label: null,
      required: null,
      type: 'LongTextArea',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: '3',
      length: '32768',
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Html: {
      fullName: null,
      externalId: null,
      label: null,
      required: null,
      type: 'Html',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: '25',
      length: '32768',
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    EncryptedText: {
      fullName: null,
      externalId: null,
      label: null,
      required: 'false',
      type: 'EncryptedText',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: '175',
      maskChar: 'asterisk',
      maskType: 'all',
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Time: {
      fullName: null,
      externalId: null,
      label: null,
      required: 'false',
      type: 'Time',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Url: {
      fullName: null,
      externalId: null,
      label: null,
      required: 'false',
      type: 'Url',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Lookup: {
      fullName: null,
      externalId: 'false',
      label: null,
      required: 'false',
      type: 'Lookup',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: 'SetNull',
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    MasterDetail: {
      fullName: null,
      externalId: 'false',
      label: null,
      required: null,
      type: 'MasterDetail',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: '0',
      deleteConstraint: null,
      reparentableMasterDetail: 'false',
      writeRequiresMasterRead: 'false',
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    ExternalLookup: {
      fullName: null,
      externalId: 'false',
      label: null,
      required: null,
      type: 'ExternalLookup',
      trackHistory: null,
      trackTrending: null,
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
    Summary: {
      fullName: null,
      externalId: 'false',
      label: null,
      required: null,
      type: 'Summary',
      trackHistory: null,
      trackTrending: 'false',
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: null,
      inlineHelpText: null,
    },
  },
  isRequired: {
    AutoNumber: {
      fullName: true,
      externalId: false,
      label: true,
      required: null,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: false,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Checkbox: {
      fullName: true,
      externalId: null,
      label: true,
      required: null,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: true,
      formula: false,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: false,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Currency: {
      fullName: true,
      externalId: null,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: false,
      formula: false,
      displayLocationInDecimal: null,
      scale: true,
      precision: true,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: false,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Date: {
      fullName: true,
      externalId: null,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: false,
      formula: false,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: false,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    DateTime: {
      fullName: true,
      externalId: null,
      label: true,
      required: null,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: false,
      formula: false,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: false,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Email: {
      fullName: true,
      externalId: false,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: false,
      defaultValue: false,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Location: {
      fullName: true,
      externalId: null,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: true,
      scale: true,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Number: {
      fullName: true,
      externalId: false,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: false,
      defaultValue: false,
      formula: false,
      displayLocationInDecimal: null,
      scale: true,
      precision: true,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: false,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Percent: {
      fullName: true,
      externalId: null,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: false,
      formula: false,
      displayLocationInDecimal: null,
      scale: true,
      precision: true,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: false,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Phone: {
      fullName: true,
      externalId: null,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: false,
      formula: false,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Picklist: {
      fullName: true,
      externalId: null,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: false,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: true,
      picklistLabel: true,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    MultiselectPicklist: {
      fullName: true,
      externalId: null,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: false,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: true,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: true,
      picklistLabel: true,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Text: {
      fullName: true,
      externalId: false,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: false,
      defaultValue: false,
      formula: false,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: true,
      maskChar: null,
      maskType: null,
      caseSensitive: false,
      formulaTreatBlanksAs: false,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    TextArea: {
      fullName: true,
      externalId: null,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: false,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    LongTextArea: {
      fullName: true,
      externalId: null,
      label: true,
      required: null,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: false,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: true,
      length: true,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Html: {
      fullName: true,
      externalId: null,
      label: true,
      required: null,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: true,
      length: true,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    EncryptedText: {
      fullName: true,
      externalId: null,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: true,
      maskChar: true,
      maskType: true,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Time: {
      fullName: true,
      externalId: null,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: false,
      formula: false,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: false,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Url: {
      fullName: true,
      externalId: null,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: false,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Lookup: {
      fullName: true,
      externalId: false,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: true,
      relationshipLabel: true,
      relationshipName: true,
      relationshipOrder: null,
      deleteConstraint: true,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    MasterDetail: {
      fullName: true,
      externalId: false,
      label: true,
      required: null,
      type: true,
      trackHistory: false,
      trackTrending: false,
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: true,
      relationshipLabel: true,
      relationshipName: true,
      relationshipOrder: true,
      deleteConstraint: null,
      reparentableMasterDetail: true,
      writeRequiresMasterRead: true,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    ExternalLookup: {
      fullName: true,
      externalId: false,
      label: true,
      required: false,
      type: true,
      trackHistory: false,
      trackTrending: null,
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: true,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: true,
      relationshipLabel: true,
      relationshipName: true,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      displayFormat: null,
      summarizedField: null,
      summaryForeignKey: null,
      summaryOperation: null,
      summaryFilterItemsField: null,
      summaryFilterItemsOperation: null,
      summaryFilterItemsValue: null,
      description: false,
      inlineHelpText: false,
    },
    Summary: {
      fullName: true,
      externalId: false,
      label: true,
      required: null,
      type: true,
      trackHistory: null,
      trackTrending: false,
      unique: null,
      defaultValue: null,
      formula: null,
      displayLocationInDecimal: null,
      scale: null,
      precision: null,
      visibleLines: null,
      length: null,
      maskChar: null,
      maskType: null,
      caseSensitive: null,
      formulaTreatBlanksAs: null,
      picklistFullName: null,
      picklistLabel: null,
      referenceTo: null,
      relationshipLabel: null,
      relationshipName: null,
      relationshipOrder: null,
      deleteConstraint: null,
      reparentableMasterDetail: null,
      writeRequiresMasterRead: null,
      summarizedField: false,
      summaryForeignKey: true,
      summaryOperation: true,
      description: false,
      inlineHelpText: false,
    },
  },
  valueSetDefaultValues: {
    valueSetDefinition: {
      sorted: 'false',
      value: [
        {
          fullName: null,
          default: 'false',
          label: null,
        },
      ],
    },
  },
  valueSetIsRequired: {
    valueSetDefinition: {
      sorted: true,
      value: [
        {
          fullName: true,
          default: true,
          label: true,
        },
      ],
    },
  },
  summaryFilterItemsDefaultValues: {
    field: null,
    operation: null,
    value: null,
  },
  summaryFilterItemsIsRequired: {
    field: true,
    operation: true,
    value: true,
  },
  options: {
    externalId: ['true', 'false'],
    required: ['true', 'false'],
    type: [
      'AutoNumber',
      'Checkbox',
      'Currency',
      'Date',
      'DateTime',
      'Email',
      'Location',
      'Number',
      'Percent',
      'Phone',
      'Picklist',
      'MultiselectPicklist',
      'Text',
      'TextArea',
      'LongTextArea',
      'Html',
      'EncryptedText',
      'Time',
      'Url',
      'Lookup',
      'MasterDetail',
      'ExternalLookup',
      'Summary',
    ],
    trackHistory: ['tue', 'false'],
    trackTrending: ['true', 'false'],
    unique: ['true', 'false'],
    defaultValue: ['true', 'false'],
    displayLocationInDecimal: ['true', 'false'],
    maskChar: ['asterisk', 'X'],
    maskType: ['all', 'lastFour', 'creditCard', 'nino', 'ssn', 'sin'],
    caseSensitive: ['true', 'false'],
    formulaTreatBlanksAs: ['BlankAsBlank', 'BlankAsZero'],
    deleteConstraint: ['Cascade', 'Restrict', 'SetNull'],
    relationshipOrder: ['0', '1'],
    reparentableMasterDetail: ['true', 'false'],
    writeRequiresMasterRead: ['true', 'false'],
    summaryOperation: ['count', 'sum', 'min', 'max'],
    summaryFilterItemsOperation: [
      'equals',
      'notEqual',
      'lessThan',
      'greaterThan',
      'lessOrEqual',
      'greaterOrEqual',
      'contains',
      'notContain',
      'startsWith',
      'includes',
      'excludes',
      'within',
    ],
  },
  indentationLength: 4,
  fieldExtension: 'field-meta.xml',
  delimiter: ',',
  picklistDelimiter: ';',
  tagNames: [
    'fullName',
    'label',
    'description',
    'inlineHelpText',
    'type',
    'externalId',
    'required',
    'unique',
    'defaultValue',
    'formula',
    'trackHistory',
    'trackTrending',
    'displayFormat',
    'displayLocationInDecimal',
    'scale',
    'precision',
    'visibleLines',
    'length',
    'maskChar',
    'maskType',
    'picklistFullName',
    'picklistLabel',
    'formulaTreatBlanksAs',
    'referenceTo',
    'relationshipLabel',
    'relationshipName',
    'relationshipOrder',
    'deleteConstraint',
    'reparentableMasterDetail',
    'writeRequiresMasterRead',
    'summaryForeignKey',
    'summaryOperation',
    'summarizedField',
    'summaryFilterItemsField',
    'summaryFilterItemsOperation',
    'summaryFilterItemsValue',
  ],
  resolveJsonModule: true,
};
export const fieldTemplateConfig = {
  template: {
    rowCheckbox: {
      fullName: 'checkbox__c',
      label: 'checkbox',
      description: 'Checkbox field.',
      inlineHelpText: '',
      type: 'Checkbox',
      externalId: 'false',
      required: '',
      unique: '',
      defaultValue: 'false',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowCurrency: {
      fullName: 'currency__c',
      label: ' currency',
      description: 'Currency field.',
      inlineHelpText: '',
      type: 'Currency',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '0',
      precision: '18',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowDate: {
      fullName: 'date__c',
      label: 'date',
      description: 'Date field.',
      inlineHelpText: '',
      type: 'Date',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowDatetime: {
      fullName: 'datetime__c',
      label: 'datetime',
      description: 'Datetime field.',
      inlineHelpText: '',
      type: 'DateTime',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowEmail: {
      fullName: 'email__c',
      label: 'email',
      description: 'Email field.',
      inlineHelpText: '',
      type: 'Email',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowLocation: {
      fullName: 'location__c',
      label: 'location',
      description: 'Location field.',
      inlineHelpText: '',
      type: 'Location',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: 'false',
      scale: '6',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowNumber: {
      fullName: 'number__c',
      label: 'number',
      description: ' Number field.',
      inlineHelpText: '',
      type: 'Number',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '0',
      precision: '18',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowPercent: {
      fullName: 'percent__c',
      label: 'percent',
      description: 'Precent field.',
      inlineHelpText: '',
      type: 'Percent',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowPhone: {
      fullName: 'phone__c',
      label: 'phone',
      description: 'Phone field.',
      inlineHelpText: '',
      type: 'Phone',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowPicklist: {
      fullName: 'picklist__c',
      label: 'picklist',
      description: 'Picklist field.',
      inlineHelpText: '',
      type: 'Picklist',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: 'Yes;No',
      picklistLabel: 'YES;NO',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowMultiselectPicklist: {
      fullName: 'multiselectPicklist__c',
      label: 'multiselectPicklist',
      description: 'MultiselectPicklist field.',
      inlineHelpText: '',
      type: 'MultiselectPicklist',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '4',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: 'a;b;c',
      picklistLabel: 'A;B;C',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowText: {
      fullName: 'text__c',
      label: 'text',
      description: 'Text field.',
      inlineHelpText: '',
      type: 'Text',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '255',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowTextArea: {
      fullName: 'textArea__c',
      label: 'textArea',
      description: 'TextArea field.',
      inlineHelpText: '',
      type: 'TextArea',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '255',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowLongTextArea: {
      fullName: 'longTextArea__c',
      label: 'longTextArea',
      description: 'LongTextArea field.',
      inlineHelpText: '',
      type: 'LongTextArea',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '3',
      length: '1000',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowHtml: {
      fullName: 'html__c',
      label: 'html',
      description: 'Html field.',
      inlineHelpText: '',
      type: 'Html',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '10',
      length: '1000',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowEncryptedText: {
      fullName: 'encryptedText__c',
      label: 'encryptedText',
      description: 'EncryptedText field.',
      inlineHelpText: '',
      type: 'EncryptedText',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '100',
      maskChar: 'asterisk',
      maskType: 'all',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowTime: {
      fullName: 'time__c',
      label: 'time',
      description: 'Time field.',
      inlineHelpText: '',
      type: 'Time',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowUrl: {
      fullName: 'url__c',
      label: 'url',
      description: 'Url field.',
      inlineHelpText: '',
      type: 'Url',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowLookup: {
      fullName: 'lookup__c',
      label: 'lookup',
      description: 'lookup field.',
      inlineHelpText: '',
      type: 'Lookup',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: 'Account',
      relationshipLabel: 'account lookup',
      relationshipName: 'accountLookup',
      relationshipOrder: '',
      deleteConstraint: 'SetNull',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowMasterDetail: {
      fullName: 'masterDetail__c',
      label: 'masterDetail',
      description: 'masterDetail field.',
      inlineHelpText: '',
      type: 'MasterDetail',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: 'Account',
      relationshipLabel: 'account lookup',
      relationshipName: 'accountMasterDetail',
      relationshipOrder: '0',
      deleteConstraint: '',
      reparentableMasterDetail: 'false',
      writeRequiresMasterRead: 'false',
      summaryForeignKey: '',
      summaryOperation: '',
      summarizedField: '',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
    rowSummary: {
      fullName: 'summary__c',
      label: 'summary',
      description: 'summary field.',
      inlineHelpText: '',
      type: 'Summary',
      externalId: '',
      required: '',
      unique: '',
      defaultValue: '',
      formula: '',
      trackHistory: '',
      trackTrending: '',
      displayFormat: '',
      displayLocationInDecimal: '',
      scale: '',
      precision: '',
      visibleLines: '',
      length: '',
      maskChar: '',
      maskType: '',
      picklistFullName: '',
      picklistLabel: '',
      formulaTreatBlanksAs: '',
      referenceTo: '',
      relationshipLabel: '',
      relationshipName: '',
      relationshipOrder: '',
      deleteConstraint: '',
      reparentableMasterDetail: '',
      writeRequiresMasterRead: '',
      summaryForeignKey: 'Custom_Object__c.Number__c',
      summaryOperation: 'sum',
      summarizedField: 'Custom_Object__c.Account__c',
      summaryFilterItemsField: '',
      summaryFilterItemsOperation: '',
      summaryFilterItemsValue: '',
    },
  },
};

export const objectConvertConfig = {
  header: [
    'fullName',
    'label',
    'description',
    'allowInChatterGroups',
    'deploymentStatus',
    'enableActivities',
    'enableBulkApi',
    'enableFeeds',
    'enableHistory',
    'enableReports',
    'enableSearch',
    'enableSharing',
    'enableStreamingApi',
    'nameFieldType',
    'nameFieldLabel',
    'nameFieldDisplayFormat',
  ],
  objectExtension: '.object-meta.xml',
};

export const objectRetrieveConfig = {
  header: [
    'fullName',
    'label',
    'description',
    'allowInChatterGroups',
    'deploymentStatus',
    'enableActivities',
    'enableBulkApi',
    'enableFeeds',
    'enableHistory',
    'enableReports',
    'enableSearch',
    'enableSharing',
    'enableStreamingApi',
    'nameFieldType',
    'nameFieldLabel',
    'nameFieldDisplayFormat',
  ],
  objectExtension: '.object',
};

export const objectGenerateConfig = {
  xmlSetting: {
    version: '1.0',
    encoding: 'UTF-8',
    xmlns: 'http://soap.sforce.com/2006/04/metadata',
  },
  defaultValues: {
    fullName: null,
    label: null,
    allowInChatterGroups: 'false',
    deploymentStatus: 'Deployed',
    enableActivities: 'false',
    enableBulkApi: 'true',
    enableHistory: 'false',
    enableReports: 'false',
    enableSearch: 'false',
    enableSharing: 'true',
    enableStreamingApi: 'true',
    description: null,
    nameFieldType: null,
    nameFieldLabel: null,
    nameFieldDisplayFormat: null,
  },
  isRequired: {
    fullName: true,
    label: true,
    allowInChatterGroups: false,
    deploymentStatus: false,
    enableActivities: false,
    enableBulkApi: false,
    enableHistory: false,
    enableReports: false,
    enableSearch: false,
    enableSharing: false,
    enableStreamingApi: false,
    description: false,
  },
  nameFieldDefaultValues: {
    nameField: {
      label: null,
      trackHistory: 'false',
      displayFormat: null,
      type: 'Text',
    },
  },
  nameFieldIsRequired: {
    nameField: {
      label: true,
      trackHistory: null,
      displayFormat: false,
      type: true,
    },
  },
  metaSettings: {
    actionOverrides: [
      {
        actionName: 'Accept',
        type: 'Default',
      },
      {
        actionName: 'Accept',
        formFactor: 'Large',
        type: 'Default',
      },
      {
        actionName: 'Accept',
        formFactor: 'Small',
        type: 'Default',
      },
      {
        actionName: 'CancelEdit',
        type: 'Default',
      },
      {
        actionName: 'CancelEdit',
        formFactor: 'Large',
        type: 'Default',
      },
      {
        actionName: 'CancelEdit',
        formFactor: 'Small',
        type: 'Default',
      },
      {
        actionName: 'Clone',
        type: 'Default',
      },
      {
        actionName: 'Clone',
        formFactor: 'Large',
        type: 'Default',
      },
      {
        actionName: 'Clone',
        formFactor: 'Small',
        type: 'Default',
      },
      {
        actionName: 'Delete',
        type: 'Default',
      },
      {
        actionName: 'Delete',
        formFactor: 'Large',
        type: 'Default',
      },
      {
        actionName: 'Delete',
        formFactor: 'Small',
        type: 'Default',
      },
      {
        actionName: 'Edit',
        type: 'Default',
      },
      {
        actionName: 'Edit',
        formFactor: 'Large',
        type: 'Default',
      },
      {
        actionName: 'Edit',
        formFactor: 'Small',
        type: 'Default',
      },
      {
        actionName: 'List',
        type: 'Default',
      },
      {
        actionName: 'List',
        formFactor: 'Large',
        type: 'Default',
      },
      {
        actionName: 'List',
        formFactor: 'Small',
        type: 'Default',
      },
      {
        actionName: 'New',
        type: 'Default',
      },
      {
        actionName: 'New',
        formFactor: 'Large',
        type: 'Default',
      },
      {
        actionName: 'New',
        formFactor: 'Small',
        type: 'Default',
      },
      {
        actionName: 'SaveEdit',
        type: 'Default',
      },
      {
        actionName: 'SaveEdit',
        formFactor: 'Large',
        type: 'Default',
      },
      {
        actionName: 'SaveEdit',
        formFactor: 'Small',
        type: 'Default',
      },
      {
        actionName: 'Tab',
        type: 'Default',
      },
      {
        actionName: 'Tab',
        formFactor: 'Large',
        type: 'Default',
      },
      {
        actionName: 'Tab',
        formFactor: 'Small',
        type: 'Default',
      },
      {
        actionName: 'View',
        type: 'Default',
      },
      {
        actionName: 'View',
        formFactor: 'Large',
        type: 'Default',
      },
      {
        actionName: 'View',
        formFactor: 'Small',
        type: 'Default',
      },
    ],
    compactLayoutAssignment: 'SYSTEM',
    enableFeeds: 'false',
    enableLicensing: 'false',
    externalSharingModel: 'Private',
    searchLayouts: '',
    sharingModel: 'ReadWrite',
    visibility: 'Public',
  },

  options: {
    allowInChatterGroups: ['true', 'false'],
    deploymentStatus: ['Deployed', 'InDevelopment'],
    enableActivities: ['true', 'false'],
    enableBulkApi: ['true', 'false'],
    enableHistory: ['true', 'false'],
    enableLicensing: ['true', 'false'],
    enableReports: ['true', 'false'],
    enableSearch: ['true', 'false'],
    enableSharing: ['true', 'false'],
    enableStreamingApi: ['true', 'false'],
    nameFieldType: ['Text', 'AutoNumber'],
  },
  indentationLength: 4,
  objectExtension: '.object-meta.xml',
  delimiter: ',',
  tagNames: [
    'label',
    'allowInChatterGroups',
    'deploymentStatus',
    'enableActivities',
    'enableBulkApi',
    'enableHistory',
    'enableReports',
    'enableSearch',
    'enableSharing',
    'enableStreamingApi',
    'nameFieldType',
    'nameFieldLabel',
    'nameFieldDisplayFormat',
    'description',
  ],
  resolveJsonModule: true,
};

export const objectTemplateConfig = {
  template: {
    rowText: {
      fullName: 'CustomObject__c',
      label: 'CustomObject',
      description: 'Custom object.',
      allowInChatterGroups: 'false',
      deploymentStatus: 'Deployed',
      enableActivities: 'false',
      enableBulkApi: 'true',
      enableHistory: 'false',
      enableReports: 'false',
      enableSearch: 'false',
      enableSharing: 'true',
      enableStreamingApi: 'true',
      nameFieldType: 'Text',
      nameFieldLabel: 'CustomObjectName',
      nameFieldDisplayFormat: '',
    },
    rowAutoNumber: {
      fullName: 'CustomObject_AutoNumber__c',
      label: 'CustomObject',
      description: 'Custom object.',
      allowInChatterGroups: 'true',
      deploymentStatus: 'InDevelopment',
      enableActivities: 'true',
      enableBulkApi: 'true',
      enableHistory: 'true',
      enableReports: 'true',
      enableSearch: 'true',
      enableSharing: 'true',
      enableStreamingApi: 'true',
      nameFieldType: 'AutoNumber',
      nameFieldLabel: 'CustomObjectName',
      nameFieldDisplayFormat: 'CustomObject-{0000}',
    },
  },
};

export const profileConvertConfig = {
  header: [
    'fullName',
    'type',
    'editable',
    'readable',
    'allowCreate',
    'allowDelete',
    'allowEdit',
    'allowRead',
    'modifyAllRecords',
    'viewAllRecords',
    'default',
    'visible',
    'enabled',
    'visibility',
  ],
  permissionTags: {
    applicationVisibilities: {
      keyTag: 'application',
      tags: ['default', 'visible'],
    },
    classAccesses: {
      keyTag: 'apexClass',
      tags: ['enabled'],
    },
    fieldPermissions: {
      keyTag: 'field',
      tags: ['editable', 'readable'],
    },
    objectPermissions: {
      keyTag: 'object',
      tags: ['allowCreate', 'allowDelete', 'allowEdit', 'allowRead', 'modifyAllRecords', 'viewAllRecords'],
    },
    pageAccesses: {
      keyTag: 'apexPage',
      tags: ['enabled'],
    },
    recordTypeVisibilities: {
      keyTag: 'recordType',
      tags: ['default', 'visible'],
    },
    tabVisibilities: {
      keyTag: 'tab',
      tags: ['visibility'],
    },
    userPermissions: {
      keyTag: 'name',
      tags: ['enabled'],
    },
  },
  profileExtension: '.profile-meta.xml',
};

export const profileRetrieveConfig = {
  header: [
    'fullName',
    'type',
    'editable',
    'readable',
    'allowCreate',
    'allowDelete',
    'allowEdit',
    'allowRead',
    'modifyAllRecords',
    'viewAllRecords',
    'default',
    'visible',
    'enabled',
    'visibility',
  ],
  permissionTags: {
    applicationVisibilities: {
      keyTag: 'application',
      tags: ['default', 'visible'],
    },
    classAccesses: {
      keyTag: 'apexClass',
      tags: ['enabled'],
    },
    fieldPermissions: {
      keyTag: 'field',
      tags: ['editable', 'readable'],
    },
    objectPermissions: {
      keyTag: 'object',
      tags: ['allowCreate', 'allowDelete', 'allowEdit', 'allowRead', 'modifyAllRecords', 'viewAllRecords'],
    },
    pageAccesses: {
      keyTag: 'apexPage',
      tags: ['enabled'],
    },
    recordTypeVisibilities: {
      keyTag: 'recordType',
      tags: ['default', 'visible'],
    },
    tabVisibilities: {
      keyTag: 'tab',
      tags: ['visibility'],
    },
    userPermissions: {
      keyTag: 'name',
      tags: ['enabled'],
    },
  },
  profileExtension: '.profile',
};

export const profileGenerateConfig = {
  xmlSetting: {
    version: '1.0',
    encoding: 'UTF-8',
    xmlns: 'http://soap.sforce.com/2006/04/metadata',
  },
  permissionTags: {
    applicationVisibilities: {
      keyTag: 'application',
      tags: ['default', 'visible'],
    },
    classAccesses: {
      keyTag: 'apexClass',
      tags: ['enabled'],
    },
    fieldPermissions: {
      keyTag: 'field',
      tags: ['editable', 'readable'],
    },
    objectPermissions: {
      keyTag: 'object',
      tags: ['allowCreate', 'allowDelete', 'allowEdit', 'allowRead', 'modifyAllRecords', 'viewAllRecords'],
    },
    pageAccesses: {
      keyTag: 'apexPage',
      tags: ['enabled'],
    },
    recordTypeVisibilities: {
      keyTag: 'recordType',
      tags: ['default', 'visible'],
    },
    tabVisibilities: {
      keyTag: 'tab',
      tags: ['visibility'],
    },
    userPermissions: {
      keyTag: 'name',
      tags: ['enabled'],
    },
  },
  options: {
    editable: ['true', 'false'],
    readable: ['true', 'false'],
    allowCreate: ['true', 'false'],
    allowDelete: ['true', 'false'],
    allowEdit: ['true', 'false'],
    allowRead: ['true', 'false'],
    modifyAllRecords: ['true', 'false'],
    viewAllRecords: ['true', 'false'],
    default: ['true', 'false'],
    visible: ['true', 'false'],
    enabled: ['true', 'false'],
    visibility: ['DefaultOn', 'DefaultOff', 'Hidden'],
  },
  indentationLength: 4,
  profileExtension: '.profile-meta.xml',
  delimiter: ',',
  resolveJsonModule: true,
};

export const tabConvertConfig = {
  header: [
    'fullName',
    'label',
    'type',
    'description',
    'customObject',
    'flexiPage',
    'frameHeight',
    'hasSidebar',
    'lwcComponent',
    'motif',
    'page',
    'splashPageLink',
    'url',
    'urlEncodingKey',
  ],
  metaSettings: {
    customObject: 'CustomObject',
    flexiPage: 'LightningPage',
    lwcComponent: 'LightningComponent',
    page: 'Visualforce',
    url: 'Web',
  },
  tabExtension: '.tab-meta.xml',
};

export const tabRetrieveConfig = {
  header: [
    'fullName',
    'label',
    'type',
    'description',
    'customObject',
    'flexiPage',
    'frameHeight',
    'hasSidebar',
    'lwcComponent',
    'motif',
    'page',
    'splashPageLink',
    'url',
    'urlEncodingKey',
  ],
  metaSettings: {
    customObject: 'CustomObject',
    flexiPage: 'LightningPage',
    lwcComponent: 'LightningComponent',
    page: 'Visualforce',
    url: 'Web',
  },
  tabExtension: '.tab',
};

export const tabGenerateConfig = {
  xmlSetting: {
    version: '1.0',
    encoding: 'UTF-8',
    xmlns: 'http://soap.sforce.com/2006/04/metadata',
  },
  defaultValues: {
    CustomObject: {
      fullName: null,
      label: null,
      type: null,
      description: null,
      customObject: null,
      flexiPage: null,
      frameHeight: null,
      hasSidebar: null,
      lwcComponent: null,
      motif: null,
      page: null,
      splashPageLink: null,
      url: null,
      urlEncodingKey: null,
    },
    Visualforce: {
      fullName: null,
      label: null,
      type: null,
      description: null,
      customObject: null,
      flexiPage: null,
      frameHeight: null,
      hasSidebar: null,
      lwcComponent: null,
      motif: null,
      page: null,
      splashPageLink: null,
      url: null,
      urlEncodingKey: null,
    },
    LightningComponent: {
      fullName: null,
      label: null,
      type: null,
      description: null,
      customObject: null,
      flexiPage: null,
      frameHeight: '600',
      hasSidebar: 'false',
      lwcComponent: null,
      motif: null,
      page: null,
      splashPageLink: null,
      url: 'https://',
      urlEncodingKey: 'UTF-8',
    },
    LightningPage: {
      fullName: null,
      label: null,
      type: null,
      description: null,
      customObject: null,
      flexiPage: null,
      frameHeight: null,
      hasSidebar: null,
      lwcComponent: null,
      motif: null,
      page: null,
      splashPageLink: null,
      url: null,
      urlEncodingKey: null,
    },
    Web: {
      fullName: null,
      label: null,
      type: null,
      description: null,
      customObject: null,
      flexiPage: null,
      frameHeight: null,
      hasSidebar: null,
      lwcComponent: null,
      motif: null,
      page: null,
      splashPageLink: null,
      url: 'https://',
      urlEncodingKey: 'UTF-8',
    },
  },
  isRequired: {
    CustomObject: {
      fullName: true,
      label: null,
      type: true,
      description: null,
      customObject: true,
      flexiPage: null,
      frameHeight: null,
      hasSidebar: null,
      lwcComponent: null,
      motif: true,
      page: null,
      splashPageLink: null,
      url: null,
      urlEncodingKey: null,
    },
    Visualforce: {
      fullName: true,
      label: true,
      type: true,
      description: null,
      customObject: null,
      flexiPage: null,
      frameHeight: null,
      hasSidebar: null,
      lwcComponent: null,
      motif: true,
      page: true,
      splashPageLink: null,
      url: null,
      urlEncodingKey: null,
    },
    LightningComponent: {
      fullName: true,
      label: true,
      type: true,
      description: null,
      customObject: null,
      flexiPage: null,
      frameHeight: null,
      hasSidebar: null,
      lwcComponent: null,
      motif: null,
      page: null,
      splashPageLink: null,
      url: null,
      urlEncodingKey: null,
    },
    LightningPage: {
      fullName: true,
      label: true,
      type: true,
      description: null,
      customObject: null,
      flexiPage: true,
      frameHeight: null,
      hasSidebar: null,
      lwcComponent: null,
      motif: null,
      page: null,
      splashPageLink: null,
      url: null,
      urlEncodingKey: null,
    },
    Web: {
      fullName: true,
      label: true,
      type: true,
      description: null,
      customObject: null,
      flexiPage: null,
      frameHeight: null,
      hasSidebar: true,
      lwcComponent: null,
      motif: true,
      page: null,
      splashPageLink: null,
      url: true,
      urlEncodingKey: true,
    },
  },
  options: {
    customObject: ['true', 'false'],
    hasSidebar: ['true', 'false'],
    urlEncodingKey: [
      'UTF-8',
      'ISO-8859-1',
      'Shift-JIS',
      'JIS',
      'EUC',
      'ks_c_5601-1987',
      'Big5',
      'GB2312',
      'Big5-HKSCS',
      'Shift-JIS_2004',
    ],
    type: ['CustomObject', 'Visualforce', 'LightningComponent', 'LightningPage', 'Web'],
  },
  indentationLength: 4,
  tabExtension: '.tab-meta.xml',
  delimiter: ',',
  resolveJsonModule: true,
};

export const tabTemplateConfig = {
  template: {
    CustomObject: {
      fullName: 'Custom_Object__c',
      label: 'Custom_Object',
      type: 'CustomObject',
      description: '',
      customObject: 'true',
      flexiPage: '',
      frameHeight: '',
      hasSidebar: '',
      lwcComponent: '',
      motif: 'Custom26: Flag',
      page: '',
      splashPageLink: '',
      url: '',
      urlEncodingKey: '',
    },
    Visualforce: {
      fullName: 'HelloWorld',
      label: 'Hello World',
      type: 'Visualforce',
      description: '',
      customObject: '',
      flexiPage: '',
      frameHeight: '',
      hasSidebar: '',
      lwcComponent: '',
      motif: 'Custom70: Handsaw',
      page: 'HelloWorld',
      splashPageLink: '',
      url: '',
      urlEncodingKey: '',
    },
    LightningComponent: {
      fullName: 'HelloWorld',
      label: 'Hello World',
      type: 'LightningComponent',
      description: '',
      customObject: '',
      flexiPage: '',
      frameHeight: '',
      hasSidebar: '',
      lwcComponent: 'HelloWorld',
      motif: 'Custom65: Cup',
      page: '',
      splashPageLink: '',
      url: '',
      urlEncodingKey: '',
    },
    LightningPage: {
      fullName: 'HelloWorld',
      label: 'Hello World',
      type: 'LightningPage',
      description: '',
      customObject: '',
      flexiPage: 'HelloWorld',
      frameHeight: '',
      hasSidebar: '',
      lwcComponent: '',
      motif: 'Custom72: Helicopter',
      page: '',
      splashPageLink: '',
      url: '',
      urlEncodingKey: '',
    },
    Web: {
      fullName: 'Web',
      label: 'Web',
      type: 'Web',
      description: '',
      customObject: '',
      flexiPage: '',
      frameHeight: '600',
      hasSidebar: 'false',
      lwcComponent: '',
      motif: 'Custom62: Chalkboard',
      page: '',
      splashPageLink: '',
      url: 'https://google.com',
      urlEncodingKey: 'UTF-8',
    },
  },
};
